[tasks.c]
command = "make"
args = ["longportwhale_c"]
cwd = "cmake.build"

[tasks.c-release]
command = "make"
args = ["longportwhale_c"]
cwd = "cmake.build"

[tasks.c.windows]
command = "msbuild"
args = ["longportwhale.sln", "-p:Configuration=Debug", "/t:longportwhale_c"]
cwd = "cmake.build"

[tasks.c-release.windows]
command = "msbuild"
args = ["longportwhale.sln", "-p:Configuration=Release", "/t:longportwhale_c"]
cwd = "cmake.build"

[tasks.c-test]
command = "make"
args = ["test-c"]
cwd = "cmake.build"

[tasks.c-test.windows]
command = "msbuild"
args = ["longport.sln", "-p:Configuration=Debug", "/t:test-c"]
cwd = "cmake.build"
