[package]
name = "whale"
version = "0.1.0"
edition = "2021"

[dependencies]
longportwhale = { path = "../../../rust" }
tokio = { version = "1.19", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

